export const AUTHENTICATE = 'AUTHENTICATE';

export const START_SIGN_IN = 'START_SIGN_IN';
export const END_SIGN_IN = 'END_SIGN_IN';

export const START_CREATE_ACCOUNT = 'START_CREATE_ACCOUNT';
export const END_CREATE_ACCOUNT = 'END_CREATE_ACCOUNT';
